Implementation of routing algorithm, fix some bug and add restriction for config
jmjos/ratatoskr pull request #90
Opened 2021-02-04 20:42 UTC by yangyt96

- This implementation of routing algorithm XYZ is compatible with older version (theoretically if there is no bug :D). 
	- This is an extension routing algorithm XYZ for 2D-Torus and Ring
	- Tested for 2D-Torus urand 100000ns: 4x4, 4x8, 8x8, 8x16, 16x16; all pass
	- Tested for Ring urand 100000ns up to 64 nodes; all pass

	- Add 3D vector tools - absolute value (38afed63981fdc5af9c763e5e1bd9434cdeeb74e)

	- The segmentation fault is fixed (dd578942292215c8245dd76cca7564abb2e6712e), which is due to the max value of bufferReportRouter equal to the amount of router 
	- Add some restriction for config to prevent some other bugs (588c6c88458848e48aa11ee59f9bf51115f71180)

TODO:
	- implementation for 3D torus and its routing algorithm
	- more updates for routing algorithm of torus

2021-02-08 12:51 UTC, jmjos requested changes
Hi! Looks good in general, except two things. Please do the following:

1. Please do not modify the bin/...py files directly. Rather, make a new package as discussed offline. I would like to keep the bin folder constant for now for legacy reasons.
2. Please add urand tests to the CI for the new topologies and routings. (see .travis.yml)
3. Please use the new packaged-python classes for the tests as much as possible.
Thanks!

2021-02-12 11:53 UTC, yangyt96 commented
I revert the commit 588c6c8, but this has removed the feature for adding "topology" into config.xml, so the simulator cannot use the new feature of ring and torus routing. Do I still need to add this topology feature (in xml_writers.py) into too? (Checkout d9bae63 bin/xml_writers.py, line 598, 600).

2021-02-12 11:55 UTC, jmjos commented
Yes, please add it. But you can add it to the "new" xml_writers.py in the ratatoskr-tools package only. That would be fine to foster migration to the new interface!

2021-02-22 16:32 UTC, yangyt96 commented
Can we make a version number after this pull request is merge? So for the ratatoskr-tools documentation can mention that the minimum version requirement for the simulator, this would be more friendly for the user :D

2021-03-01 08:55 UTC, yangyt96 commented
> Hi! Looks good in general, except two things. Please do the following:
> 
> 1. Please do not modify the bin/...py files directly. Rather, make a new package as discussed offline. I would like to keep the bin folder constant for now for legacy reasons.
> 2. Please add urand tests to the CI for the new topologies and routings. (see .travis.yml)
> 3. Please use the new packaged-python classes for the tests as much as possible.
>    Thanks!

It is done with this package :D #89 #92
https://github.com/jmjos/ratatoskr-tools/tree/dev-yang

2021-03-08 16:46 UTC, jmjos approved these changes

2021-03-08 16:46 UTC, merged